/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame_clases;

import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import project.AL_dueño;
import project.Registro;
import project.AL_mascota;

/**
 *
 * @author reyna
 */
public class register extends javax.swing.JFrame {
      public static AL_mascota accesoAleatorio=new AL_mascota();
    Registro n=new Registro();
    /**
     * Creates new form register
     */
    public register() {
        this.setTitle("Registros");
        this.setVisible(true);
        initComponents();
        
        if(!jRadioButton1.isSelected()){
        jButton1.setEnabled(false);}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        NAME = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NAMEU = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PASSWORD1 = new javax.swing.JPasswordField();
        PASSWORD = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        EMAIL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        DATE = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nombre completo :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nombre de usuario :");

        NAMEU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMEUActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Contraseña :");

        PASSWORD1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PASSWORD1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PASSWORD1FocusLost(evt);
            }
        });
        PASSWORD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASSWORD1ActionPerformed(evt);
            }
        });
        PASSWORD1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PASSWORD1KeyTyped(evt);
            }
        });

        PASSWORD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PASSWORDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PASSWORDFocusLost(evt);
            }
        });
        PASSWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASSWORDActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Confirmar Contraseña :");

        EMAIL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                EMAILFocusLost(evt);
            }
        });
        EMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMAILActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Correro electronico :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Fecha de nacimiento :");

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("SI");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("No");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("¿Has leido los terminos de Condicion?");

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NAMEU, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(NAME)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PASSWORD1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(PASSWORD)
                            .addComponent(EMAIL)
                            .addComponent(DATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NAMEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PASSWORD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(DATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(31, 31, 31)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMAILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EMAILActionPerformed

    private void NAMEUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMEUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMEUActionPerformed

    private void PASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASSWORDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PASSWORDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(Vacio(NAME)&&Vacio(NAMEU)&&Vacio(PASSWORD)&&Vacio(PASSWORD1)&&Vacio(DATE)&&Vacio(EMAIL)){
           Date novoa=new Date();
            double fechaFocal=((double)DATE.getDate().getYear())+((double)DATE.getDate().getMonth())/100+((double)DATE.getDate().getDay())/1000,
                    fechaActual=((double)novoa.getYear())+((double)novoa.getMonth())/100+((double)novoa.getDay())/1000;
            if(fechaFocal<0)
            {JOptionPane.showMessageDialog(null,"Lamento decirle que usted o es un ente maligno, bebio algun remedio de la abuelita que estaba bien hecho o simplemente estas mintiendo sobre tu edad","Verificacion de edad",JOptionPane.ERROR_MESSAGE);
           return;
            }
            
        int edad=(int)((-1)*(fechaFocal-fechaActual));
        
           if(!PASSWORD.getText().equals(PASSWORD1.getText()))
         {
             JOptionPane.showMessageDialog(null,"Las contraseñas no coinciden por lo tanto verifique y corrija ese error","Verificacion de Contraseña",JOptionPane.ERROR_MESSAGE);
            
             return;
         }
        if(edad<0)
        {
            JOptionPane.showMessageDialog(null,"Es relativamente imposible tener una edad menor a la actual","Verificacion de edad",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
      if(Verificando(EMAIL)==false)
        {JOptionPane.showMessageDialog(null,"El correo electronico no es reconocido como tal, lo mas posible es que falta cietos caracteres como '@'","Verificacion de Correo Electronico",JOptionPane.ERROR_MESSAGE);
            return;
            
        }
        JOptionPane.showMessageDialog(null,"!Felicidades¡ Se ha registrado","Notificacion de registro",JOptionPane.INFORMATION_MESSAGE);
            
         
           
               /*
               if(n.addDueño(edad, NAME.getText(),DATE.getDate().toString() , PASSWORD.getText(),NAMEU.getText(),EMAIL.getText()))
               {
               n.show();}*/try {
               AL_dueño.CrearFileDueño(new File("Dueños.dat"));
                   AL_dueño.añadirDueño(new Dueño(NAMEU.getText(),edad, NAME.getText(),DATE.getDate().toString() , PASSWORD.getText(),EMAIL.getText()));
              AL_dueño.cerrar();
           } catch (IOException ex) {
               Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
       else{JOptionPane.showMessageDialog(null,"Faltan datos para la completacion del registro","Datos Incompletos", JOptionPane.PLAIN_MESSAGE);}
      /* this.setVisible(false);
          NewJFrame a=new NewJFrame();
         a.setVisible(true);*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        jButton1.setEnabled(false);
        
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        LOGIN n=new LOGIN();
        n.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.setVisible(false);
        LOGIN a=new LOGIN();
        a.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void PASSWORD1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PASSWORD1KeyTyped
       
    }//GEN-LAST:event_PASSWORD1KeyTyped

    private void PASSWORD1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PASSWORD1FocusLost
       if(Vacio(PASSWORD)&&Vacio(PASSWORD1))
       {if(PASSWORD.getText().equals(PASSWORD1.getText()))
            {
                jLabel8.setVisible(false);
                Color r=new Color(255,255,255);
                PASSWORD1.setBackground(r);
                System.out.println(PASSWORD.getText().equals(PASSWORD1.getText()));
                
            }
       else{
          
           jLabel8.setVisible(true);
           jLabel8.setText("las Contraseñas no coinciden");
           PASSWORD1.setForeground(Color.black);
           PASSWORD1.setBackground(Color.red);
            }
       }
       
    }//GEN-LAST:event_PASSWORD1FocusLost

    private void PASSWORD1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PASSWORD1FocusGained
if(Vacio(PASSWORD)&&Vacio(PASSWORD1))
       {if(PASSWORD.getText().equals(PASSWORD1.getText()))
            {
                jLabel8.setVisible(false);
                Color r=new Color(255,255,255);
                PASSWORD1.setBackground(r);
                System.out.println(PASSWORD.getText().equals(PASSWORD1.getText()));
                
            }
       else{
          
           jLabel8.setVisible(true);
           jLabel8.setText("Contraseñas no coinciden");
           PASSWORD1.setForeground(Color.black);
           PASSWORD1.setBackground(Color.red);
            }
       }
    }//GEN-LAST:event_PASSWORD1FocusGained

    private void PASSWORD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASSWORD1ActionPerformed
       if(Vacio(PASSWORD)&&Vacio(PASSWORD1))
       {if(PASSWORD1.getText().equals(PASSWORD1))
            {
                jLabel8.setVisible(false);
                Color r=new Color(255,255,255);
                PASSWORD1.setBackground(r);
               System.out.println("sd");
                
                
            }}
    }//GEN-LAST:event_PASSWORD1ActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
      if(Vacio(PASSWORD)&&Vacio(PASSWORD1))
       {if(PASSWORD1.getText().equals(PASSWORD1))
            {System.out.println("move");
                jLabel8.setVisible(false);
                Color r=new Color(255,255,255);
                PASSWORD1.setBackground(r);
                
                
            }}
    }//GEN-LAST:event_formMouseMoved

    private void PASSWORDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PASSWORDFocusGained
      if(Vacio(PASSWORD)&&Vacio(PASSWORD1))
       {if(PASSWORD.getText().equals(PASSWORD1.getText()))
            {jLabel8.setVisible(false);
                jLabel8.setText("coinciden");
                Color r=new Color(255,255,255);
                PASSWORD1.setBackground(r);
                
                
            }
       else{
           jLabel8.setVisible(true);
           jLabel8.setText("Contraseñas no coinciden");
           PASSWORD1.setForeground(Color.black);
           PASSWORD1.setBackground(Color.red);
            }
       }
    }//GEN-LAST:event_PASSWORDFocusGained

    private void PASSWORDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PASSWORDFocusLost
       if(Vacio(PASSWORD)&&Vacio(PASSWORD1))
       {if(PASSWORD.getText().equals(PASSWORD1.getText()))
            {jLabel8.setVisible(false);
                jLabel8.setText("coinciden");
                Color r=new Color(255,255,255);
                PASSWORD1.setBackground(r);
                
                
            }
       else{
           jLabel8.setVisible(true);
           jLabel8.setText("Contraseñas no coinciden");
           PASSWORD1.setForeground(Color.black);
           PASSWORD1.setBackground(Color.red);
            }
       }
    }//GEN-LAST:event_PASSWORDFocusLost

    private void EMAILFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EMAILFocusLost
        Color r= new Color(255,255,255);
        if(Vacio(EMAIL))
        {   int cont=0;
            char temp[]=EMAIL.getText().toCharArray();
            for(int i=0;i<temp.length;i++)
            {
                if(temp[i]=='@')
                {
                    cont++;
                }
            }
            if(cont!=1)
            {
                EMAIL.setBackground(Color.red);
            }
            else{ EMAIL.setBackground(r);}
            if(EMAIL.getText().endsWith(".es")||EMAIL.getText().endsWith(".com")){EMAIL.setBackground(r); }
            else{EMAIL.setBackground(Color.red);}
            
        }
    }//GEN-LAST:event_EMAILFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DATE;
    private javax.swing.JTextField EMAIL;
    private javax.swing.JTextField NAME;
    private javax.swing.JTextField NAMEU;
    private javax.swing.JPasswordField PASSWORD;
    private javax.swing.JPasswordField PASSWORD1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
public boolean Vacio(JTextField temp)
{
    if(temp.getText().length()<=0)
    {
        return false;
    }
    else{
        return true;
    }
}
public boolean Vacio(JPasswordField temp)
{
    if(temp.getText().length()<=0)
    {
        return false;
    }
    else{
        return true;
    }
}
public boolean Vacio(JDateChooser temp)
{   try{
    if(temp.getDate().toString().length()<=0||temp.getCalendar().toString().length()<=0)
    {
        return false;
    }
    else{
        
        return true;
    }
    }catch(NullPointerException e){
    return false;
    }

}
public boolean Verificando(JTextField GMAIL)
    {
        Color r= new Color(255,255,255);
        if(Vacio(GMAIL))
        {   int cont=0;
            char temp[]=GMAIL.getText().toCharArray();
            for(int i=0;i<temp.length;i++)
            {
                if(temp[i]=='@')
                {
                    cont++;
                }
            }
            if(cont!=1)
            {
                GMAIL.setBackground(Color.red);
                return false;
            }
            else{ GMAIL.setBackground(r);}
            if(GMAIL.getText().endsWith(".es")||GMAIL.getText().endsWith(".com")){
            GMAIL.setBackground(r);
                System.out.println("nani");}
            else{GMAIL.setBackground(Color.red);
                return false;}
         return true;   
        }
        else{return true; }
    }
}
